//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PackerTest.rc
//

#define IDD_PROGRESS_METER              1105
#define IDD_ADD_FILES					1106

#define IDI_PACKER_TEST                 1101

#define IDC_ADD_FILES_SELECT_ALL_FILE   1214
#define IDC_ADD_FILES_SELECT_ALL_EXT    1215
#define IDC_ADD_FILES_DESELECT_ALL_EXT  1220
#define IDC_ADD_FILES_DESELECT_ALL_FILE 1221
#define IDC_ADD_FILES_EXT_FRAME         1226
#define IDC_ADD_FILES_EXTENSIONS_FRAME  1227
#define IDC_PROGRESS_METER_CAPTION      1102
#define IDC_PROGRESS_METER_BAR          1103
#define IDC_PROGRESS_METER_ACTIVITY     1104
#define IDC_ADD_FILES_EXTENSION			1107
#define IDC_ADD_FILES_FILE				1108
#define IDC_ADD_FILES_SELECT_ALL		1109
#define IDC_ADD_FILES_DESELECT_ALL		1110
#define IDC_ADD_FILES_COUNT				1111

#define	IDD_CHECKIN						1200
#define IDD_SCRIPT_CONFLICT				1201

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        400
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1500
#define _APS_NEXT_SYMED_VALUE           112
#endif
#endif
