//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Co-op.rc
//
#define ID_CAPTION                      100
#define ID_COOP                         101
#define ID_WWW_PURCHASE_BC              102
#define IDD_NEW_PROJECT_PAGE            102
#define IDD_NEW_FILE                    103
#define ID_WWW_PURCHASE_GUIFFY          103
#define I_LOCKED                        104
#define IDD_PROJECT_DEFECT              105
#define IDB_BUTTONS                     106
#define IDD_CHECKIN                     107
#define IDB_BMP_RS                      108
#define IDD_ABOUT                       109
#define IDD_PROJECT_MEMBERS             110
#define IDD_FILE_TYPE                   111
#define I_SYN_NEW                       112
#define I_SYN_DEL                       113
#define I_SYN                           114
#define I_FOLDER                        115
#define I_NONE                          116
#define I_IN                            117
#define I_OUT                           118
#define I_NEW                           119
#define I_DEL                           120
#define I_SCRIPT                        121
#define I_IN_SCRIPT                     122
#define I_OUT_SCRIPT                    123
#define I_NEXT_SCRIPT                   124
#define I_CUT                           125
#define ID_VIEWTABS                     126
#define ID_TEXTCLASS                    127
#define ID_TOOLBAR                      128
#define ID_DIFFCLASS                    129
#define IDD_LICENSE_CHECK               130
#define ID_TOOLBAR_DROPDOWN             131
#define I_MISSING_SCRIPT                132
#define ID_WWW_HOME_PAGE                133
#define IDD_SCRIPT_RECIPIENTS           135
#define ID_WWW_PURCHASE_LICENSE         136
#define ID_TOOLBARTEXT                  137
#define IDD_SAVE_OLD_FILES              139
#define ID_WWW_LICENSE                  140
#define ID_SUPPORT                      141
#define IDD_BEGINNER_MODE               143
#define IDD_SCRIPT_CONFLICT             144
#define IDD_NEW_PROJECT_ADD_FILES       145
#define IDD_ADD_FILES                   146
#define IDD_EXPORT_PROJECT              147
#define I_VERSION                       148
#define I_VERSION_CUR                   149
#define I_VERSION2                      150
#define I_LABEL                         151
#define IDD_REVERT_INFO                 152
#define IDD_CHECKSUM_MISMATCH           155
#define IDD_VERIFY_PROJECT_REPORT       156
#define I_AWAITING                      157
#define IDD_PROJECT_ADMIN               158
#define I_PROJECT                       159
#define I_CURPROJ                       160
#define I_SYN_PROJ                      161
#define I_VRANGE1                       162
#define I_VRANGE2                       163
#define I_TAB_RED                       164
#define IDD_FILE_TYPE_CHANGE            165
#define IDD_MOVE_PROJECT                167
#define ID_LICENSE_TEXT                 168
#define IDD_LICENSE_AGREEMENT           169
#define IDD_JOIN_PATH                   170
#define IDD_FILE_DROP                   171
#define IDD_FOLDER_DROP                 172
#define IDD_ADD_DROP                    173
#define I_FOLDER_IN                     174
#define IDD_CHECKIN_NO_CHANGES          175
#define I_VIEWER                        176
#define I_WAIT                          177
#define I_REJECTED_SCRIPT               178
#define I_TAB_YELLOW                    179
#define IDS_FIRST_HELP                  200
#define IDS_ADDFILE                     201
#define IDS_CHECKOUT                    202
#define IDS_CHECKIN                     203
#define IDS_UNPACK                      204
#define IDS_JOIN                        205
#define IDS_RESTORE                     206
#define IDS_NEWFILE                     207
#define IDS_UNCHECKOUT                  208
#define IDS_REMOVE                      209
#define IDS_DELETE                      210
#define IDS_RENAME                      211
#define IDS_CUT                         212
#define IDS_PASTE                       213
#define IDS_ACCEPT                      214
#define IDS_SENDSCRIPT                  215
#define IDS_NOPROJECT                   216
#define IDS_COPY                        217
#define IDD_SCRIPT_HEADER               219
#define IDS_THIS_SCRIPT_CHANGES         219
#define IDD_FILE_DETAILS                220
#define IDS_SINCE_THIS_SCRIPT_CHANGES   221
#define IDS_COMPARE_SCRIPT_CHANGES      222
#define IDS_MERGELOCALBRANCH            223
#define IDS_MERGE_NOCONFLICTS           224
#define IDD_DEFECT                      225
#define IDS_GLOBALMERGE                 225
#define IDS_MERGE_NOMERGER              226
#define IDD_CTRL_SCRIPT                 226
#define IDS_LAST_HELP                   227
#define IDD_INCOMING_MEMBERSHIP_UPDATE  227
#define IDS_NOTREADY                    228
#define ID_HIERARCHYVIEW                229
#define I_CUR_OUT_PROJ                  230
#define I_OUT_PROJ                      231
#define IDD_UPDATE_HUB_ID               232
#define I_MERGE                         233
#define I_FOLDERO                       234
#define I_FOLDERCG                      235
#define I_FOLDEROG                      236
#define I_FOLDERC                       237
#define IDD_HIDE_EXTENSIONS             238
#define IDD_PROJECT_INVITE              239
#define I_PROJOPEN                      240
#define I_PROJCLOSED                    241
#define I_SORTUP                        242
#define I_SORTDOWN                      243
#define ID_WWW_SUPPORT_PAGE             244
#define IDD_ONE_FILE_DROP               245
#define IDD_ONE_FOLDER_DROP             246
#define IDD_ADD_ONE_DROP                247
#define ID_ITEMVIEW                     248
#define IDI_PROJECT_MEMBER              249
#define IDI_VERIFIED_MEMBER             250
#define IDI_ADMINISTRATOR               251
#define IDD_PROMPT_MODE                 252
#define IDI_THIS_MEMBER                 253
#define IDI_THIS_VERIFIED_MEMBER        254
#define IDD_RECEIVER_JOIN               255
#define IDD_SAVE_DIAGNOSTICS            256
#define IDD_SELECT_FILE                 257
#define IDD_PROJECT_BRANCH_PAGE         258
#define I_FULL_SYN                      259
#define I_VERSION_R                     260
#define I_VERSION_CUR_R                 261
#define I_VERSION2_R                    262
#define I_VRANGE1_R                     263
#define I_VRANGE2_R                     264
#define IDS_SCC_PROMPT                  265
#define IDD_MERGE_FILE_ATTRIBUTES       266
#define IDD_SELECT_PROJECT              267
#define IDD_EXPORT_HTML                 268
#define IDD_SAVE_FILE                   270
#define I_RECOVERY_PROJ                 271
#define IDD_FTP_OPEN_FILE               272
#define I_MERGE_CONFLICT                274
#define IDD_MOVE_FILES                  275
#define IDC_PROJECT_NAME_LABEL          1003
#define IDC_NEW_PROJECT_NAME_EDIT       1004
#define IDC_NEW_PROJECT_SOURCE_EDIT     1006
#define IDC_NEW_FILE_FNAME_EDIT         1009
#define IDC_NEW_FILE_HEADER             1010
#define IDC_NEW_FILE_SOURCE             1011
#define IDC_NEW_FILE_OTHER              1012
#define IDC_NEW_FILE_KIND_FRAME         1013
#define IDC_NEW_FILE_FNAME_LABEL        1014
#define IDC_NEW_FILE_COPYRIGHT_EDIT     1015
#define IDC_NEW_FILE_COPYRIGHT_FRAME    1016
#define IDC_NEW_FILE_DEFAULT            1017
#define IDC_NEW_FILE_USE_COPYRIGHT      1018
#define IDC_NEW_FILE_BINARY             1019
#define IDC_NEW_FILE_DEFINE             1020
#define IDC_NEW_FILE_WIKI               1021
#define IDC_PROJ_DEFECT_DELETE_FILES    1034
#define IDC_PROJ_DEFECT_DELETE_ALL      1035
#define IDC_USER_NAME_LABEL             1036
#define IDC_PROJ_DEFECT_DELETE_HISTORY  1037
#define IDC_USER_EMAIL_LABEL            1040
#define IDC_USER_PHONE_LABEL            1041
#define IDC_NEW_PROJECT_USER_NAME       1042
#define IDC_NEW_PROJECT_USER_PHONE      1043
#define IDC_USER_FRAME                  1045
#define IDC_CHECKIN_COMMENT             1054
#define IDC_JOIN_PROJECT_OBSERVER       1055
#define IDC_PROJECT_MEMBERS_LIST        1056
#define IDC_JOIN_PROJ_ADMIN_NAME_LABEL  1057
#define IDC_FILE_TYPER_HEADER           1058
#define IDC_FILE_TYPER_SOURCE           1059
#define IDC_FILE_TYPER_TEXT             1060
#define IDC_FILE_TYPER_BINARY           1061
#define IDC_FILE_TYPER_EXT              1062
#define IDC_FILE_TYPER_EXT_LABEL        1063
#define IDC_FILE_TYPER_ADD              1064
#define IDC_FILE_TYPE_EXT_LABEL         1065
#define IDC_FILE_TYPER_WIKI             1066
#define IDC_NEW_FILE_FRAME_FOLDER       1069
#define IDC_NEW_FILE_PATH               1070
#define IDC_EDIT_MEMBER_NAME            1072
#define IDC_EDIT_MEMBER_EMAIL           1073
#define IDC_EDIT_MEMBER_PHONE           1074
#define IDC_EDIT_MEMBER_NAME_LABEL      1075
#define IDC_EDIT_MEMBER_EMAIL_LABEL     1076
#define IDC_EDIT_MEMBER_PHONE_LABEL     1077
#define IDC_EDIT_MEMBER_VOTING          1078
#define IDC_EDIT_MEMBER_OBSERVER        1079
#define IDC_EDIT_MEMBER_REMOVED         1080
#define IDC_DATA_PATH_FRAME             1082
#define IDC_NEW_PROJECT_OPTION_FRAME    1085
#define IDC_JOIN_PROJECT_NAME_FRAME     1086
#define IDC_USER_NAME                   1087
#define IDC_USER_EMAIL                  1088
#define IDC_USER_PHONE                  1089
#define IDC_PROJECT_NAME                1090
#define IDC_PROJECT_PATH                1091
#define IDC_BUTTON_WWW                  1092
#define IDC_LICENSE_KEEP_EVALUATING     1093
#define IDC_USER_LICENSE                1094
#define IDC_LICENSE_PURCHASE            1095
#define IDC_BUTTON_LICENSE              1096
#define IDC_LICENSE_REGISTER            1097
#define IDC_LICENSEE_LABEL              1098
#define IDC_KEY_LABEL                   1099
#define IDC_LICENSEE_EDIT               1100
#define IDC_KEY_EDIT                    1101
#define IDC_LICENSEE_TEXT               1102
#define IDC_FRAME_WEB_SITE              1103
#define IDC_SCRIPT_RECIPIENTS_LIST      1104
#define IDC_VIEW_OLD_FILES_LIST         1105
#define IDC_SAVE_OLD_FILES_TARGET       1109
#define IDC_SAVE_OLD_FILES_TARGET_BROWSE 1110
#define IDC_SAVE_OLD_FILES_OVERWRITE    1111
#define IDC_SAVE_OLD_FILES_FOLDERS      1112
#define IDC_BEGINNER_MODE_DONOT_SHOW    1123
#define IDC_BEGINNER_MODE_TEXT          1124
#define IDC_STATIC_SOURCE               1125
#define IDC_STATIC_SCRIPTS              1126
#define IDC_STATIC_FILES                1127
#define IDC_SCRIPT_CONFLICT_SCRIPT      1129
#define IDC_SCRIPT_CONFLICT_FILE        1130
#define IDC_SCRIPT_CONFLICT_VERSION     1131
#define IDC_ADD_FILES_COUNT             1132
#define IDC_ADD_FILES_EXTENSION         1135
#define IDC_ADD_FILES_FILE              1136
#define IDC_EXPORT_PROJECT_FRAME        1139
#define IDC_EXPORT_PROJECT_VERSION      1140
#define IDC_EXPORT_PROJECT_BROWSE_FRAME 1141
#define IDC_EXPORT_PROJECT_TARGET_EDIT  1142
#define IDC_REVERT_INFO_VERSION_FRAME   1143
#define IDC_REVERT_INFO_VERSION         1144
#define IDC_MODE_FRAME                  1149
#define IDC_SCRIPT_CONFLICT_AUTO        1150
#define IDC_SCRIPT_CONFLICT_MANUAL      1151
#define IDC_REPAIR_FILE_LIST            1152
#define IDC_REPAIR_INFO                 1153
#define IDC_CHECKSUM_FRAME              1154
#define IDC_CHECKSUM_OPTION_FRAME       1155
#define IDC_CHECKSUM_REPAIR             1156
#define IDC_CHECKSUM_ADVANCED           1157
#define IDC_CHECKSUM_FILES              1158
#define IDC_MISSING_FILE_FRAME          1159
#define IDC_MISSING_FILE_LIST           1160
#define IDC_DESCRIPTION_FRAME           1162
#define IDC_STATUS_FRAME                1163
#define IDC_LICENSE_FRAME               1164
#define IDC_EDIT_STATIC_INFO            1165
#define IDC_NEW_ADMIN                   1166
#define IDC_CURRENT_ADMIN_FRAME         1167
#define IDC_ADMIN_NAME_LABEL            1168
#define IDC_ADMIN_EMAIL_LABEL           1169
#define IDC_ADMIN_ID_LABEL              1170
#define IDC_ADMIN_NAME                  1171
#define IDC_ADMIN_EMAIL                 1172
#define IDC_ADMIN_ID                    1173
#define IDC_NEW_ADMIN_FRAME             1174
#define IDC_NEW_ADMIN_INFO              1175
#define IDC_CHECKIN_LAST_COMMENT        1177
#define IDC_VIEW_OLD_FILES_FRAME        1178
#define IDC_CHECKIN_KEEPCHECKEDOUT      1179
#define IDC_FILE_TYPE_HEADER            1180
#define IDC_FILE_TYPE_SOURCE            1181
#define IDC_FILE_TYPE_TEXT              1182
#define IDC_FILE_TYPE_BINARY            1183
#define IDC_FILE_TYPE_EXT               1184
#define IDC_FILE_TYPE_ADD               1185
#define IDC_TYPE_FILE_KIND_FRAME        1186
#define IDC_PROJ_OPTIONS_SHORT_SCRIPT_FILE_NAME 1187
#define IDC_PROJ_OPTIONS_AUTO_SYNCH     1188
#define IDC_NEW_SRC                     1190
#define IDC_BROWSE                      1191
#define IDC_EDIT_MEMBER_ADMIN           1192
#define IDC_LICENSE_AGREEMENT_TEXT      1193
#define IDC_LICENSE_DONT_NAG            1194
#define IDC_EDIT                        1195
#define IDC_FILE_DROP_TARGET_ICON       1199
#define IDC_FILE_DROP_TARGET_SIZE       1200
#define IDC_FILE_DROP_TARGET_DATE       1201
#define IDC_DROP_INFO                   1202
#define IDC_FILE_DROP_SOURCE_ICON       1203
#define IDC_FILE_DROP_SOURCE_SIZE       1204
#define IDC_FILE_DROP_SOURCE_DATE       1205
#define IDC_PROJ_MOVE_FILES             1206
#define IDC_PROJ_MOVE_ALL               1207
#define IDC_NEW_FILE_BROWSE             1208
#define IDC_PROJECT_MEMBERS_EDIT        1209
#define IDC_NEW_PROJECT_BROWSE_SOURCE   1210
#define IDC_JOIN_PROJECT_BROWSE_SOURCE  1211
#define IDC_SCRIPT_RECIPIENTS_SELECT_ALL 1212
#define IDC_VIEW_OLD_FILES_SELECT_ALL   1213
#define IDC_ADD_FILES_SELECT_ALL_FILE   1214
#define IDC_ADD_FILES_SELECT_ALL_EXT    1215
#define IDC_EXPORT_PROJECT_TARGET_BROWSE 1216
#define IDC_DROP_YESTOALL               1217
#define IDC_SCRIPT_RECIPIENTS_DESELECT_ALL 1218
#define IDC_VIEW_OLD_FILES_DESELECT_ALL 1219
#define IDC_ADD_FILES_DESELECT_ALL_EXT  1220
#define IDC_ADD_FILES_DESELECT_ALL_FILE 1221
#define IDC_DROP_NO                     1222
#define IDC_VIEW_OLD_FILES_DIFF         1223
#define IDC_DROP_NOTOALL                1224
#define IDC_VIEW_OLD_FILES_SAVE         1225
#define IDC_VIEW_OLD_FILES_SAVE_NEWER   1225
#define IDC_ADD_FILES_EXT_FRAME         1226
#define IDC_VIEW_OLD_FILES_SAVE_OLDER   1226
#define IDC_VIEW_OLD_FILES_HIDE_UNCHANGED 1227
#define IDC_CHECKIN_FRAME               1228
#define IDC_CHECKIN_COMMENT_EDIT        1229
#define IDC_LINEAGE_FRAME               1230
#define IDC_LINEAGE                     1231
#define IDC_MEMBER_FRAME                1232
#define IDC_MEMBER_LIST                 1233
#define IDC_FILE_DETAILS_LIST           1234
#define IDC_SCRIPTID                    1235
#define IDC_SCRIPT_SENDER               1236
#define IDC_SCRIPT_DATE                 1237
#define IDC_SCRIPT_TYPE                 1237
#define IDC_MEMBER_ID                   1238
#define IDC_MEMBER_NAME                 1239
#define IDC_MEMBER_EMAIL                1240
#define IDC_MEMBER_PHONE                1241
#define IDC_MEMBER_LICENSE              1242
#define IDC_MEMBER_LABEL                1243
#define IDC_CAPTION                     1244
#define IDC_MEMBER_STATE                1245
#define IDC_MEMBERSHIP_HISTORY          1246
#define IDC_CURRENT_MEMBERSHIP          1247
#define IDC_MEMBER_DATA_CHANGES         1247
#define IDC_MEMBERSHIP_UPDATE           1248
#define IDC_MEMBERSHIP_HISTORY_ACK_LIST 1249
#define IDC_CAPTION2                    1250
#define IDC_CAPTION3                    1251
#define IDC_PROJ_OPTIONS_KEEP_CHECKED_OUT 1252
#define IDC_KEEP_CHECKED_OUT            1253
#define IDC_SCRIPT_BRANCHID             1254
#define IDC_SCRIPT_MEMBERSHIPID         1255
#define IDC_USER_ADDRESS                1256
#define IDC_CATALOG_HUB_ID              1257
#define IDC_EXPORT_LOCAL_EDITS          1258
#define IDC_HIDEN_EXTENSIONS            1260
#define IDC_ADD_EXTENSIONS              1261
#define IDC_HIDE_SELECT_ALL             1262
#define IDC_HIDE_DESELECT_ALL           1263
#define IDC_UNHIDE                      1264
#define IDC_ADD_EDIT                    1265
#define IDC_ADD_EXTENSION               1266
#define IDC_ADD_SCAN_OR_SELECT_ALL      1267
#define IDC_ADD_DESELECT_ALL            1268
#define IDC_SCAN_PROGRESS               1269
#define IDC_INVITE_INFO                 1270
#define IDC_INVITE_CLIPBOARD            1271
#define IDC_INVITE_FILE                 1272
#define IDC_PROJ_OPTIONS_AUTO_JOIN      1273
#define IDC_HIDE_NON_PROJECT            1274
#define IDC_FILE_DETAILS_OPEN           1275
#define IDC_FILE_DETAILS_OPENALL        1276
#define IDC_ABOUT                       1277
#define IDC_USER_ID                     1278
#define IDC_HUB_ID                      1279
#define IDC_SAVE_OLD_FILES_LOCAL_EDITS  1280
#define IDC_CHUNK_COUNT                 1280
#define IDC_MAX_CHUNK                   1281
#define IDD_DIFFER_OPTIONS              1282
#define IDC_VIEW_OLD_FILES_FILTER       1283
#define IDD_MISSING_SCRIPT              1284
#define IDC_RECEIVED_CHUNK_COUNT        1285
#define IDC_VIEW_OLD_FILES_FILTER_STRING 1286
#define IDD_RESEND_OPTIONS              1287
#define IDC_EXPORT_OVERWRITE            1288
#define IDC_PROMPT_MODE_DONOT_SHOW      1289
#define IDD_COOP_UPDATE_OPTIONS         1290
#define IDC_RADIO_DIFFER                1291
#define IDC_RADIO_BC                    1292
#define IDC_PROMPT_MODE_TEXT            1293
#define IDC_PROMPT_ICON                 1294
#define IDC_BEGINNER_ICON               1295
#define IDC_REQUEST_RECIPIENTS          1296
#define IDC_NEXT_RECIPIENT              1297
#define IDC_NEXT_RESEND_CAPTION         1298
#define IDC_DIFFER_OPTIONS_BUILTIN      1299
#define IDC_DIFFER_OPTIONS_BC           1300
#define IDC_DIFFER_OPTIONS_BUILTIN_BC   1301
#define IDC_DIFFER_OPTIONS_BC_ORIGINAL  1302
#define IDC_RESEND_OPTIONS_PERIOD       1303
#define IDC_RESEND_OPTIONS_DELAY        1304
#define IDC_RESEND_OPTIONS_REPEAT       1305
#define IDC_COOP_UPDATE_OPTIONS_AUTO_CHECK 1306
#define IDC_COOP_UPDATE_OPTIONSD_PERIOD_EDIT 1307
#define IDC_COOP_UPDATE_OPTIONS_PERIOD_SPIN 1308
#define IDC_COOP_UPDATE_OPTIONS_IN_BACKGROUND 1309
#define IDD_CHUNKING_OPTIONS            1310
#define IDC_CHUNKING_OPTIONS_SIZE       1311
#define IDD_OVERDUE_SCRIPT              1311
#define IDD_NEW_PROJECT_PAGE1           1312
#define IDD_PROJECT_OPTIONS_PAGE        1312
#define IDC_CHUNKING_OPTIONS_WARNING    1313
#define IDD_PROJECT_DISTRIBUTOR         1313
#define IDD_NEW_PROJECT_OPTIONS_PAGE    1314
#define IDC_OVERDUE_MEMBER_LIST         1315
#define IDD_PROJECT_ENCRYPTION          1315
#define IDC_BUTTON                      1316
#define IDC_COPY_TO_CLIPBOARD           1317
#define IDC_BUTTON2                     1317
#define IDD_MERGER_OPTIONS              1317
#define IDB_LICENSE                     1318
#define IDC_DISTRIBUTOR                 1319
#define IDC_JOIN_CAPTION                1320
#define IDC_STATE_FRAME                 1321
#define IDC_RECEIVER                    1322
#define IDC_VOTING                      1323
#define IDC_FULL_MEMBER                 1323
#define IDC_LICENSED                    1325
#define IDC_PROJ_OPTIONS_DISTRIBUTOR    1326
#define IDC_LICENSE                     1326
#define IDC_POOL                        1328
#define IDC_ASSIGN                      1329
#define IDC_DISTRIBUTOR_STATUS          1329
#define IDC_LICENSE_POOL                1330
#define IDC_DISTRIBUTOR_LICENSE         1330
#define IDC_GUIFFY                      1331
#define IDC_PROJ_OPTIONS_DISALLOW_BRANCHING 1332
#define IDC_ARAXIS                      1332
#define IDC_DIAG_HISTORY                1335
#define IDC_DIAG_TARGET_FILE            1336
#define IDC_SELECT_TARGET_FILE          1336
#define IDC_SELECT_TARGET_PATH          1337
#define IDC_TARGET_PATH_BROWSE          1340
#define IDC_PROJ_OPTIONS_SINGLE_TO_RECIPIENT 1341
#define IDC_RADIO2                      1342
#define IDC_PROJ_OPTIONS_ALL_BCC_RECIPIENTS 1342
#define IDC_SELECT_FILE_FRAME           1343
#define IDC_DISTRIBUTOR_FRAME           1344
#define IDC_SELECT_OVERWRITE            1345
#define IDC_BRANCH_VERSION_FRAME        1346
#define IDC_BRANCH_VERSION              1347
#define IDC_BRANCH_TARGET_FRAME         1348
#define IDC_BRANCH_TARGET               1349
#define IDC_BRANCH_TARGET_BROWSE        1350
#define IDC_BRANCH_PROJECT_NAME         1351
#define IDC_BRANCH_CREATOR_FRAME        1352
#define IDC_BRANCH_PROJECT_USER         1353
#define IDC_BRANCG_PROJECT_COMMENT      1354
#define IDC_VIEW_OLD_FILES_COMMENT_FRAME 1355
#define IDC_RADIO1                      1356
#define IDC_RADIO3                      1357
#define IDC_RADIO4                      1358
#define IDC_COPYRIGHT                   1359
#define IDC_FILE_TYPER_EXT_FRAME        1360
#define IDC_FRAME                       1361
#define IDC_PROJECT_INVITE_OBSERVER     1362
#define IDC_PROJECT_INVITE_PEER_OR_HUB  1363
#define IDC_PROJECT_INVITE_SAT          1364
#define IDC_PROJECT_INVITE_SAT_NAME     1365
#define IDC_PROJECT_INVITE_EMAIL        1366
#define IDC_PROJECT_INVITE_STATIC_EMAIL 1367
#define IDC_PROJECT_INVITE_PROJNAME     1368
#define IDC_PROJECT_INVITE_STATIC_SAT   1369
#define IDC_FRAME2                      1370
#define IDC_PROJECT_INVITE_USERNAME     1371
#define IDC_PROJ_OPTIONS_ENCRYPT        1372
#define IDC_PROJ_OPTIONS_ENCRYPT_PASS   1373
#define IDC_PROJ_OPTIONS_ENCRYPT_PASS2  1374
#define IDC_PROJ_OPTIONS_STATIC2        1375
#define IDC_PROJ_OPTIONS_STATIC         1376
#define IDC_PROJ_OPTIONS_COMMON_PASS    1377
#define IDC_PROJ_OPTIONS_WIKI           1378
#define IDC_SAVE_OLD_FILES_VERSION_BEFORE 1379
#define IDC_SAVE_OLD_FILES_VERSION_AFTER 1380
#define IDC_REVERT_INFO_DETAILS         1381
#define IDC_SCRIPT_CONFLICT_OPTIONS     1382
#define IDC_CURRENT_VERSION_FRAME       1385
#define IDC_CURRENT_NAME                1386
#define IDC_CURRENT_PATH                1387
#define IDC_CURRENT_TYPE                1388
#define IDC_BRANCH_NAME                 1389
#define IDC_BRANCH_PATH                 1390
#define IDC_BRANCH_TYPE                 1391
#define IDC_MERGE_VERSION_FRAME         1392
#define IDC_MERGE_NAME                  1393
#define IDC_MERGE_PATH                  1394
#define IDC_MERGE_TYPE                  1395
#define IDC_USE_CURRENT_NAME            1397
#define IDC_USE_CURRENT_PATH            1398
#define IDC_USE_CURRENT_TYPE            1399
#define IDC_USE_BRANCH_NAME             1400
#define IDC_MERGER_OPTIONS_BC_COOP      1400
#define IDC_USE_BRANCH_PATH             1401
#define IDC_MERGER_OPTIONS_BC_ORIGINAL  1401
#define IDC_USE_CURRENT_NAME3           1402
#define IDC_USE_BRANCH_TYPE             1402
#define IDC_PROJECT_LIST                1403
#define IDC_EDIT_PATH                   1404
#define IDC_BUTTON_BROWSE               1405
#define IDC_EDITOR_PATH                 1406
#define IDC_EDITOR_CMD                  1407
#define IDC_EDITOR_PATH_BROWSE          1408
#define IDC_EDITOR_OPTIONS_BUILTIN      1409
#define IDC_EDITOR_OPTIONS_EXTERNAL     1410
#define IDD_EDITOR_OPTIONS              1411
#define IDC_MERGER_OPTIONS_BC           1412
#define IDD_INVITATION_OPTIONS          1412
#define IDC_MERGER_OPTIONS_BUILTIN_BC   1413
#define IDD_VERIFICATION_REQUEST_RECIPIENTS 1413
#define IDC_MERGER_OPTIONS_ORIGINAL_BC  1414
#define IDD_OPEN_FILE                   1414
#define IDC_OPTIONS_AUTO_INVITE         1415
#define IDD_SELECT_ROOT_PATH            1415
#define IDC_OPTIONS_PATH                1416
#define IDD_PROJECT_INVITE_OPTIONS      1416
#define IDC_OPTIONS_BROWSE              1417
#define IDD_BACKUP_SUMMARY              1417
#define IDC_BACKUP_NAME                 1418
#define IDD_CHECKEDOUT_BY               1418
#define IDC_FILE_NAME                   1418
#define IDD_SAVE_FILE_NOTE              1419
#define IDD_SCRIPT_CONFLICT_OPTIONS     1420
#define IDC_LOCAL_SOURCE_PATH           1422
#define IDC_BACKUP_LAN_SERVER           1423
#define IDC_BACKUP_INTERNET_SERVER      1424
#define IDC_FTP_SERVER                  1424
#define IDC_MY_COMPUTER_BROWSE          1425
#define IDC_LAN_BROWSE                  1426
#define IDC_FTP_BROWSE                  1426
#define IDC_OVERWRITE_EXISTING          1427
#define IDC_FTP_USER                    1429
#define IDC_FTP_PASSWORD                1430
#define IDC_ANONYMOUS_LOGIN             1431
#define IDC_FTP_FOLDER                  1432
#define IDC_RECIPIENTS_LIST             1433
#define IDC_FTP_FILENAME                1433
#define IDC_DLG_CAPTION                 1434
#define IDC_OPTION_CHECKBOX             1435
#define IDC_SCRIPT_CONFLICT_AUTOMERGE   1436
#define IDC_SCRIPT_CONFLICT_EXECUTEONLY 1437
#define IDC_SCRIPT_CONFLICT_POSTPONE    1438
#define IDC_FTP_CURRENT_FOLDER          1439
#define IDC_FTP_GOUP                    1440
#define IDC_FTP_FOLDER_CONTENT          1441
#define IDC_FTP_CURRENT_FOLDER2         1442
#define IDC_FTP_CURRENT_FILE            1442
#define IDC_MANUAL_SEND_INVITATION      1443
#define IDC_ROOT_PATH_LIST              1444
#define IDC_ROOT_PATH_BROWSE            1445
#define IDC_COMBO1                      1446
#define IDC_DRIVE_SELECTOR              1446
#define IDC_BROWSE_NETWORK              1447
#define IDC_SAVE_INVITATION             1448
#define IDC_SAVE_HISTORY                1449
#define IDC_LOCAL_FOLDER                1450
#define IDC_MY_COMPUTER                 1451
#define IDC_INTERNET                    1452
#define IDC_CHECK1                      1455
#define IDC_START_CHECKOUT_NOTIFICATIONS 1455
#define IDC_FILENAME_FRAME              1458
#define IDC_STORE_FRAME                 1459
#define IDC_TARGET_FOLDER               1460
#define IDC_FILE_FRAME                  1461
#define IDC_USER_NOTE                   1461
#define IDC_OPTIONS_RESOLVE_QUIETLY     1462
#define IDC_SAVE_OLD_DELETE_NON_EXISTING 1463
#define IDC_SAVE_OLD_PERFORM_DELETES    1463
#define IDC_BUTTON_REMOVE               1464
#define IDC_BUTTON_DETAILS              1465
#define IDC_LIST                        1466
#define IDC_EDIT2                       1468

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        276
#define _APS_NEXT_COMMAND_VALUE         40039
#define _APS_NEXT_CONTROL_VALUE         1470
#define _APS_NEXT_SYMED_VALUE           180
#endif
#endif
