//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Dispatcher.rc
//
#define ID_MAIN                         1
#define ID_CAPTION                      2
#define IDC_TEST_STOP                   2
#define IDC_TEST_START                  3
#define IDS_REMOTE_TAB_NAME             3
#define IDC_HELP_BUTTON                 4
#define IDS_STANDALONE_INFO             4
#define ID_TAB_RED                      9
#define ID_BUTTONS                      101
#define ID_STATUSBAR                    102
#define TASKBAR_ICON_ID                 105
#define ID_TOOLBAR                      106
#define ID_NOSCRIPTS                    107
#define ID_TABS                         107
#define ID_WAITING_SCRIPTS              108
#define ID_INVALID                      109
#define ID_TOOLBARTEXT                  110
#define ID_ALERT                        114
#define IDD_FWD_FOLDER_JOIN             115
#define IDD_WHAT_WITH_SCRIPT            117
#define IDD_UNKNOWN_USE_EMAIL           125
#define IDD_HEADER                      128
#define IDD_BAD_SCRIPT                  131
#define IDD_COPY_FAILED                 133
#define IDD_ABOUT                       134
#define ID_OUT_SCRIPTS                  137
#define ID_IN_SCRIPTS                   138
#define IDD_DIAGNOSTICS                 140
#define IDD_FWD_FOLDER_RECEIVE          142
#define IDD_WIZARD_INTRO                145
#define IDD_WIZARD_ROLE_LAN             146
#define IDD_WIZARD_HUB_PATH             148
#define IDD_WIZARD_DIAGNOSTICS          149
#define IDD_WIZARD_AUTOMATIC            150
#define IDD_WIZARD_FINISH               152
#define IDD_WIZARD_ROLE_EMAIL_LAN       153
#define IDD_UNKNOWN_INTRO               155
#define IDD_UNKNOWN_HUB_PATH            157
#define IDD_ALERT                       158
#define IDD_UNKNOWN_CONFIG_ERROR        159
#define IDD_ALERT_1                     160
#define ID_USERS                        161
#define ID_USER                         162
#define ID_ENVELOPE                     164
#define ID_EXUSER                       165
#define ID_SATUSER                      166
#define ID_EXSATUSER                    167
#define IDD_FWD_PATH_CHANGE             168
#define IDD_PURGE                       169
#define IDD_UNKNOWN_PROJECT_NAME        170
#define IDD_UNKNOWN_MISSPELLED          171
#define IDD_UNKNOWN_ADDRESSEE           172
#define IDD_UNKNOWN_EMAIL               173
#define IDD_UNKNOWN_INTRO_JOIN          175
#define IDD_UNKNOWN_HUB_OR_SAT          176
#define IDD_UNKNOWN_LAN_OR_IGNORE_JOIN  179
#define IDD_UNKNOWN_LAN_OR_IGNORE       180
#define IDD_UNKNOWN_SAT_PATH            181
#define IDD_UNKNOWN_STANDALONE_TO_LAN   182
#define IDD_UNKNOWN_STANDALONE_TO_LAN_JOIN 183
#define IDD_UNKNOWN_STANDALONE_JOIN     184
#define IDD_UNKNOWN_STANDALONE          185
#define IDD_JOIN_PROJECT                186
#define IDD_HUB_ID_HUB                  187
#define IDD_HUB_ID_SAT                  188
#define IDD_HUBTRANSPORT                189
#define ID_REMOTE_HUB                   190
#define IDD_STANDALONE_JOIN             191
#define IDD_STANDALONE_JOIN_SOURCE      192
#define IDD_STANDALONE_JOIN_USER        193
#define IDD_REMOTE_HUB_TRANSPORT        194
#define IDD_COLLABORATION_SIMPLE        195
#define IDD_COLLABORATION_TEMP_HUB      197
#define IDD_EMAIL_DIAGNOSTICS           198
#define IDD_EMAIL_PROCESSING            199
#define IDD_COLLABORATION_REMOTE_SAT    201
#define ID_PC                           202
#define IDD_MY_NETWORK_PROPERTIES       203
#define ID_MAIL                         204
#define IDD_NETWORK_PROPERTIES          205
#define ID_LONGARROW                    206
#define ID_PCGRAY                       207
#define ID_LAPTOP                       208
#define ID_SHORTARROW                   209
#define ID_WIRELEFT                     210
#define ID_WIRERIGHT                    211
#define IDD_COLLABORATION_HUB           212
#define IDD_COLLABORATION_SAT           213
#define IDD_HUB_ID_TRANSPORT            214
#define IDD_EMAIL_GENERAL               215
#define ID_SHARE                        216
#define ID_ARROWUP                      218
#define ID_ARROWDOWN                    219
#define ID_BRACE                        220
#define IDD_REMOTE_HUB_TRANS            221
#define IDD_WIZARD_HUB_ID               222
#define IDD_UP_TO_DATE                  223
#define IDD_UPDATE                      224
#define IDD_UPDATE_OPTIONS              227
#define ID_ALERT_WAITING                228
#define ID_ALERT_IN                     229
#define ID_ALERT_OUT                    230
#define ID_ALERT_NO                     231
#define IDD_JOIN_PROJECT_OPTIONS        234
#define IDD_DISTRIB_TRANSFER            235
#define IDD_INVITE_SAT_PATH             236
#define IDD_POP3                        237
#define IDD_SMTP                        238
#define ID_ALERT_ACTIVITY               239
#define ID_ERROR                        240
#define IDD_INVITE_OFFSITE_SAT_TRANSPORT 241
#define IDD_PROJECT_INVITE              242
#define IDD_REJECTED_INVITATION         243
#define ID_ALERT_LOG                    244
#define IDD_WIZARD_EMAIL_TECHNOLOGY     244
#define IDD_WIZARD_EMAIL_POP3           244
#define IDD_WIZARD_EMAIL_POP3SMTP       244
#define IDD_WIZARD_EMAIL_SMTP           245
#define IDD_WIZARD_EMAIL_GMAIL          245
#define IDD_WIZARD_EMAIL_SELECTION      246
#define ID_GMAIL_POP3                   247
#define ID_TAB_YELLOW                   249
#define IDD_EMAIL_PASSWORD              250
#define IDD_EMAIL_PROMPT                251
#define IDD_WIZARD_FINISH1              252
#define IDD_WIZARD_RESTORE              252
#define IDD_WIZARD_HUB_EMAIL_SELECTION  253
#define ID_MAINVIEW                     401
#define IDC_BROWSE                      1014
#define IDC_REJECT                      1015
#define IDC_PREFS_FWD_BROWSE            1019
#define IDC_RECIPIENTS                  1022
#define IDC_EMAIL                       1027
#define IDB_BROWSE                      1029
#define ID_PATH_EDIT                    1030
#define IDC_PREFS_SEND_AUTOMATIC        1038
#define IDC_PREFS_SEND_MANUAL           1039
#define IDC_NOTICE                      1042
#define IDC_PROJECT                     1056
#define IDC_LOCATION                    1057
#define IDC_PATH                        1058
#define IDC_PREPRO_PROGRAM              1063
#define IDC_PREPRO_RESULT               1064
#define IDC_POSTPRO_EXT                 1065
#define IDC_POSTPRO_PROGRAM             1066
#define IDC_NAME                        1071
#define IDC_FILENAME                    1072
#define IDC_FORWARD                     1101
#define IDC_DEFECT                      1102
#define IDC_SCRIPT                      1114
#define IDC_DEST                        1115
#define IDC_WHY                         1116
#define IDC_WHAT                        1117
#define IDC_TEST_STATUS_FRAME           1129
#define IDC_TEST_STATUS                 1130
#define IDC_TEST_PROGRESS               1131
#define IDC_PREFS_SHARE_LABEL           1145
#define IDC_PREFS_SHARE_EDIT            1146
#define IDC_PREFS_FWD_EDIT              1147
#define IDC_STATUS                      1148
#define IDC_FWD_JOIN_HINT               1153
#define IDC_FWD_PROJECT                 1154
#define IDC_FWD_EMAIL                   1155
#define IDC_FWD_PATH_EDIT               1156
#define IDC_FWD_BROWSE                  1165
#define IDC_DIAG_TEST_KIND_FRAME        1168
#define IDC_TEST_EMAIL                  1169
#define IDC_TEST_FORWARD                1171
#define IDC_STANDALONE                  1173
#define IDC_LAN                         1174
#define IDC_BOTH                        1176
#define IDC_HUB                         1177
#define IDC_SAT                         1178
#define IDC_MISTAKE                     1179
#define IDC_SHORTCUT                    1188
#define IDC_PROJ_OPTIONS_AUTO_SYNCH     1188
#define IDC_PROJ_OPTIONS_AUTO_FULL_SYNCH 1189
#define IDC_AUTOMATIC                   1190
#define IDC_MANUAL                      1191
#define IDC_DIAG                        1198
#define IDC_FEEDBACK                    1199
#define IDC_NOT_IN_PROJECT              1210
#define IDC_ON_SATELLITE                1211
#define IDC_IS_REMOTE                   1212
#define IDC_ALERT_TEXT                  1218
#define IDC_ALERT_COUNTER               1219
#define IDC_AUTO_RECEIVE                1220
#define IDC_AUTO_RECEIVE_PERIOD         1221
#define IDC_AUTO_RECEIVE_PERIOD_SPIN    1223
#define IDC_PREFS_PI_PATH               1226
#define IDC_COMMENT                     1227
#define IDC_LOCAL                       1233
#define IDC_MISSPELLED                  1235
#define IDC_CORRECT                     1236
#define IDC_DESCRIPTION                 1239
#define IDC_MAXEMAIL                    1240
#define IDC_AUTO_RECEIVE_LAST_PART      1241
#define IDC_PROJECT_NAME                1243
#define IDC_MAXEMAILSTATIC1             1245
#define IDC_MAXEMAILSTATIC2             1246
#define IDC_TEST_EMAIL_LABEL            1247
#define IDC_TEST_MY_EMAIL               1248
#define IDC_PROJ_OPTIONS_KEEP_CHECKED_OUT 1252
#define IDC_HUB_EMAIL                   1254
#define IDC_JOIN_PROJECT_SOURCE_EDIT    1256
#define IDC_JOIN_PROJECT_FRAME          1257
#define IDC_JOIN_PROJECT_ADMINISTRATOR_FRAME 1258
#define IDC_JOIN_PROJ_USER_FRAME        1259
#define IDC_JOIN_PROJ_NAME_LABEL        1260
#define IDC_JOIN_PROJ_PHONE_LABEL       1262
#define IDC_JOIN_PROJECT_USER_NAME      1263
#define IDC_JOIN_PROJECT_USER_PHONE     1265
#define IDC_JOIN_PROJECT_ADMIN_HUB_ID   1266
#define IDC_JOIN_REMOTE_CLUSTER_HUB_ID  1266
#define IDC_JOIN_PROJECT_OBSERVER       1267
#define IDC_JOIN_PROJ_ADMIN_NAME_LABEL  1268
#define IDC_JOIN_PROJECT_NAME_FRAME     1269
#define IDC_JOIN_PROJECT_BROWSE_SOURCE  1270
#define IDC_HUB_ID                      1271
#define IDC_USER_ID                     1272
#define IDC_READEDIT                    1273
#define IDC_EDIT                        1274
#define IDC_HUB_ID_NEW                  1275
#define IDC_LOCAL_PROJECTS              1276
#define IDC_NOT_LOCAL                   1277
#define IDC_SOURCE_PATH                 1278
#define IDC_TRANSPORT                   1279
#define IDC_TRANSPORT_TYPE              1280
#define IDC_HUB_REMOTE_TRANS            1281
#define IDC_PEER                        1283
#define IDC_EMAIL_PROPERTIES            1284
#define IDC_SATELLITE                   1285
#define IDC_EMAIL_POP3SMTP              1285
#define IDC_EMAIL_SMTP                  1285
#define IDC_NETWORK_PROPERTIES          1286
#define IDC_MY_EMAIL                    1287
#define IDC_MY_NETWORK_PROPERTIES       1290
#define IDC_REMOTE_SATELLITE            1293
#define IDC_TEMP_HUB                    1294
#define IDC_EMAIL_USAGE                 1296
#define IDC_EMAIL_STATIC                1298
#define IDC_NETWORK_STATIC              1299
#define IDC_HUB_IMAGE                   1300
#define IDC_SAT_IMAGE                   1301
#define IDC_HUB_SHARE                   1302
#define IDC_SAT_SHARE                   1303
#define IDC_JOIN_THIS_CLUSTER           1304
#define IDC_JOIN_REMOTE_CLUSTER         1305
#define IDC_CHECK                       1306
#define IDC_STANDALONE_IMAGE            1307
#define IDC_SEND_UNPROCESSED            1307
#define IDC_PEER_IMAGE                  1308
#define IDC_SHARE_IMAGE                 1309
#define IDC_SHARE2_IMAGE                1310
#define IDC_SAT2_IMAGE                  1311
#define IDC_ABOUT                       1312
#define IDC_AUTO_CHECK                  1313
#define IDC_PERIOD_EDIT                 1315
#define IDC_PERIOD_SPIN                 1316
#define IDC_IN_BACKGROUND               1317
#define IDC_RELEASE_NOTES               1318
#define IDC_BULLETIN_LINK               1324
#define IDC_BULLETIN_HEADLINE           1325
#define IDC_REMIND_LATER                1326
#define IDC_COMBO                       1327
#define IDC_LIST                        1328
#define IDC_THIS_CLUSTER_HUB_ID         1329
#define IDC_JOIN_REMOTE_CLUSTER_TRANSPORT 1330
#define IDC_JOIN_LOCAL_PROJECTS         1331
#define IDC_EDIT1                       1332
#define IDC_EDIT3                       1334
#define IDC_EDIT2                       1334
#define IDC_DELETE                      1335
#define IDC_CHECK1                      1336
#define IDC_TURN_ON_AUTO_DOWNLOAD       1336
#define IDC_USE_SSL                     1336
#define IDC_COPYRIGHT                   1337
#define IDC_REPLACE_ALL                 1338
#define IDC_STATIC_SEND_USING_MAPI      1339
#define IDC_SMTP                        1340
#define IDC_STATIC_NO_SMTP              1341
#define IDC_RADIO_SEND_USING_MAPI       1342
#define IDC_RADIO_USING_SMTP            1343
#define IDC_STATIC_RECV_USING_MAPI      1344
#define IDC_STATIC_NO_POP3              1345
#define IDC_RADIO_RECV_USING_MAPI       1346
#define IDC_RADIO_USING_POP3            1347
#define IDC_POP3                        1348
#define IDC_SERVER                      1349
#define IDC_USER                        1350
#define IDC_PASSW                       1351
#define IDC_PASSW2                      1352
#define IDC_SMTPSERVER                  1352
#define IDC_AUTH                        1353
#define IDC_SMTP_USER                   1354
#define IDC_DONT_DELETE                 1355
#define IDC_SMTP_PASSW                  1355
#define IDC_USER_NAME                   1356
#define IDC_SMTP_PASSWORD_VERIFY        1356
#define IDC_AUTH_SAME_AS_POP3           1357
#define IDC_COMPUTER_NAME               1358
#define IDC_SAT_EXISTS                  1359
#define IDC_REMOVE_SCRIPT               1360
#define IDC_NET_SAT                     1361
#define IDC_OFF_SAT                     1362
#define IDC_OFFSITE_SAT_EMAILS          1363
#define IDC_INFO                        1364
#define IDC_EXPLANATION                 1365
#define IDC_PORT_NUMBER                 1366
#define IDC_EMAIL_PROGRAM               1368
#define IDC_STATIC_EMAIL                1369
#define IDC_STATIC_LOGON                1370
#define IDC_STATIC_USER                 1371
#define IDC_STATIC_PASSWORD             1372
#define IDC_STATIC_PASSWORD2            1372
#define IDC_STATIC_SERVER               1373
#define IDC_STATIC_POP3                 1374
#define IDC_STATIC_SMTP                 1375
#define IDC_POP3SERVER                  1376
#define IDC_STATIC_INFO                 1377
#define IDC_EMAIL_POP3                  1378
#define IDC_EMAIL_GMAIL                 1379
#define IDC_POP3_USER                   1379
#define IDC_POP3_PASSW                  1380
#define IDC_PASSWORD_EMAIL              1381
#define IDC_POP3_PASSWORD_VERIFY        1381
#define IDC_PASSWORD_USER               1382
#define IDC_PASSWORD_POP3               1383
#define IDC_PASSWORD_SAMEASPOP3         1384
#define IDC_PASSWORD_DIFFERENT          1385
#define IDC_PASSWORD_SMTP               1386
#define IDC_PASSWORD_POP3_VERIFY        1387
#define IDC_PASSWORD_SMTP_VERIFY        1388
#define IDC_PASSWORD_SMTP_USE           1389
#define IDC_EMAIL_EDIT                  1390
#define IDC_JOIN_THIS_COMPUTER          1391
#define IDC_ADVANCED_POP3SMTP           1392
#define IDC_PASSWORD_VERIFY             1393
#define IDC_SCRIPT_INFO_FRAME           1394

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        251
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1395
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
