#--------------------------------
# (c) Reliable Software 2002
#--------------------------------

CodeCoop.chm : CodeCoop.hhp "TableOfContents.hhc" Index.hhk "ReleaseNotes.html" FAQs\*.html Help\*.html Tutorial\*.html Images\*.gif Images\*.css
	-hhc CodeCoop.hhp

clean :
	del CodeCoop.chm
